#!/bin/bash

set -x

TMPDIR=$(mktemp -d)

boot docs \
  && cp -R target/docs "$TMPDIR" \
  && git checkout gh-pages \
  && rm -rf target/ \
  && cp -Rf "$TMPDIR/" . \
  && rm -rf "$TMPDIR" \
  && git add --all \
  && git commit -m "Update API documentation" \
  && git push origin gh-pages \
  && git checkout master
